name: Publish to gh-pages branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install rust toolchain
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable
          targets: x86_64-unknown-linux-gnu

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build and push to gh-pages
        run: |
          git config --local user.email "eq-mdbook@users.noreply.github.com"
          git config --local user.name "Equilibrium Mdbook Builder"

          git worktree add /tmp/book gh-pages
          mdbook build
          rm -rf /tmp/book/*
          cp -rp book/* /tmp/book/
          cd /tmp/book
          git add -A
          git commit -m 'new mdbook render'
          git push origin gh-pages
          cd -
